---
config:
  theme: mc
---
architecture-beta

  group g_ui(internet) [Web UI]
  group g_entraid(internet) [Azure]
  group g_llms(internet)[LLMs]
  group g_mcp[System Backend]
  group g_db[Audit Log]
  group g_opa[Policy Server]
  group g_ext(internet)[External Services]
  group g_opa_policy(internet)[OPA Policy Repositories]

  service web(server)[Web UI] in g_ui
  service entraid(server)[Entra ID] in g_entraid
  service agent(brain)[Agent_Orchestrator] in g_ui
  service orchestration(brain)[OpenAI API] in g_llms
  service http_wrapper(server)[HTTP Wrapper] in g_mcp
  service mcp(server)[GongRzhe_fldc Gmail MCP Server] in g_mcp
  service extsvc(cloud)[Gmail API] in g_ext
  service auditlog(database)[ImmuDB] in g_db
  service opa(server)[Open Policy Agent] in g_opa
  service opal_server(server)[OPAL_Server] in g_opa
  service opal_client(server)[OPAL_Client] in g_opa
  service opa_policy_repo(server)[OPA Policy Repository] in g_opa_policy


  web:L --> R:entraid
  web:T --> B:agent
  agent:T --> B:orchestration
  agent:R --> L:http_wrapper
  http_wrapper:R --> L:mcp
  http_wrapper:B --> T:auditlog
  http_wrapper:T --> B:opa
  mcp:R --> L:extsvc
  opa_policy_repo:L --> R:opal_server
  opal_client:B --> T:opa
  opal_server:L --> R:opal_client